Feature/9 show route on the map
lat-02-mobile/lat02-routes-android pull request #12
Opened 2022-09-05 19:40 UTC by Rodrigo-Schar

-added UI and draw route
-fix maps key
-merge route list by category
-added show route from list
-merge route list fix
-fix model
-change icons

2022-09-06 13:34 UTC, YawarValeriano approved these changes
Seems good

2022-09-06 13:36 UTC, jmacboy requested changes

2022-09-06 13:36 UTC, jmacboy commented on app/src/main/java/com/jalasoft/routesapp/ui/routes/view/RouteSelectedFragment.kt
> +        addStopMarkers(route!!.stops)
never force unwrap variables, validate if this route and nmap are different than null first

2022-09-06 13:36 UTC, jmacboy commented on app/src/main/java/com/jalasoft/routesapp/ui/routes/view/RouteSelectedFragment.kt
> +                mMap!!.addPolyline(
same here with the force unwrapping

2022-09-06 13:36 UTC, jmacboy commented on app/src/main/java/com/jalasoft/routesapp/ui/routes/view/RouteSelectedFragment.kt
> +                mMap!!.addPolyline(
same here with the force unwrapping

2022-09-06 13:36 UTC, jmacboy commented on app/src/main/java/com/jalasoft/routesapp/util/helpers/GoogleMapsHelper.kt
> +        vectorDrawable.draw(canvas)
no need for all these "below line" comments

2022-09-07 13:38 UTC, jmacboy approved these changes

2022-09-07 14:42 UTC, merged